sudo: required

dist: trusty

services:
  - docker

language: java

cache:
  directories:
  - "$HOME/.cache"

env:
  global:
    - DOCKER_USERNAME=cytomineulg
    - secure: "hd7Jy7ruF46HGqXCH9BdwJdeQ9DYGybC4tNEDjdYyLWmu3gQBhiEdDIJoLRyoy78qlY0iU7N2+/Tr6Z77Br560qxEpCieSLBcWde9oQGM3sM9A6igA4Zo5MQIUI7H4rDOTCz2iAnmBTOSsdU5y7IV4EuJpbEmZ5XZ4okwy+aHQAaJG/HNXoFQKbb96sM4sV+N/lnbb+HXSfcfvPpbm8LrXocwqHbzbKeMhje9O51sbdElx3qZmcWhgYerrKqbiFqhvg/7B/SB5dIMR/VPIRC7d5YAqByLWT0cECGL1XK2bKvVUecxJzfs44DDqmcEeD7thZ92xfsB8NxqNQtKX5fTR3RLlM+DhGprkpUc0sEscx7z9QHTT3k2Z7ot+loUcKSbJlYQ6898aMzMw8lVmsgPTLXmwonnwEhTze56xwwMIOi8NAWbkvsfS6uSC0nEqay+Aj+N0Ff3AjuakIly+qpZefQSlaxEqUBhebbW8O9fOyLmlQqNs0GXSgcemEkOPzs99ohww+Tn1T66UGZujadM43AbyzJxGoEjheBlX34HHFQ8CJBsKe8w6RbvaSexMKicvkbjq4+m3sMIGH1uvaWkx6UtD2u0Qd/V86InTwJ7w3KF/3tTn9HKWMrjy8D3byrssu50mreScFFgI2qVm9kr0L6ymB9MKqzJ4BHSMpFRUc="

after_success:
  - git fetch --tags
  - export VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
  - export DEPLOY=false
  - >
    if [[ ! $(git tag -l v$VERSION) ]]; then
      git config --local user.name "$(git log -1 --pretty=format:'%an')";
      git config --local user.email "$(git log -1 --pretty=format:'%ae')";
      git tag "v$VERSION";
      export DEPLOY=true;
      echo "Deploy with version $VERSION";
      cp target/*.jar docker;
      docker build --build-arg BASE_IMAGE=openjdk --build-arg BASE_TAG=8 --build-arg RELEASE_PATH="." --build-arg VERSION=$VERSION -t cytomineuliege/software-java8-base:v$VERSION docker/;
      docker build --build-arg BASE_IMAGE=openjdk --build-arg BASE_TAG=8-slim --build-arg RELEASE_PATH="." --build-arg VERSION=$VERSION -t cytomineuliege/software-java8-base:v$VERSION-slim docker/;
      docker build --build-arg BASE_IMAGE=urubens/groovy --build-arg BASE_TAG=2.5-jdk --build-arg RELEASE_PATH="." --build-arg VERSION=$VERSION -t cytomineuliege/software-groovy-base:v$VERSION docker/;
    fi;

before_deploy: "mvn package"

deploy:
  - provider: script
    script: >
      echo $VERSION &&
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" &&
      docker push cytomineuliege/software-java8-base:v$VERSION &&
      docker push cytomineuliege/software-java8-base:v$VERSION-slim &&
      docker push cytomineuliege/software-groovy-base:v$VERSION &&
      echo "Done."
    skip_cleanup: true
    on:
      condition: $DEPLOY = true
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
    skip_cleanup: true
    on:
      condition: $DEPLOY = true
  - provider: releases
    api_key:
      secure: K8BvmLKQjCtrvsTnO3KD9FDhN5iOoK0xHoysTxTTgH1jNDWdSORNmfw8ZYvh359te/SQanYLrLdFRgyuuhLk0Ww9+uzDyl/U9SmjRqdn/2+DKy4paJOV/V4z0uGKL6f9IbwfmAbO/SXeLcTVb3S7X/wmTn/0KZ7BjvsI6DV0EKZE8ka7ySthczX0gvZgumMieAKn9KvxJJQyry5vo5R8l2kRX52qE+Oc0X5p2v9hSeQETGbAwF+WBzuivqsOIP5n9lU5fPVhGuY5VZfXWUedpzVHHJC5Dwjm0Hi/l7xKjMOUTuGun/FfsIgsm2C/e8HTmFLhbRCltg0gNnGjbHgQWhhYLAtGB/BgHOfBgoyFW++aZtIVayTl67NHgLmcn8dz0loepBTEyCSi7lmOGJZaCg3RDNm929K0ukV1uPNRWof75dvVRiE75L0vgHtscfXynG7mEAVOkGsTCOQow6DRrNv5JpB4dX6Zet43jLyOFHiKiTEdusHoXVXRzzaQYRFYwEaL4I/wmck4/Dk8sqcLkN1nUUAvAV/sQS10dexC8YEA6TXSBOJrrhhnXH2KwLTnxO+LuIUAc6S/DnUvssiaCF6+KLFMNeGc7MxWs7Nj2oBNxrqRp1p7lfDr+C5s3idrAUfRYH4Fi2XuDv/cHgLbngmUiLBbkvcqvI6XiHyhJHA=
    file_glob: true
    file: target/*
    skip_cleanup: true
    on:
      condition: $DEPLOY = true
notifications:
  email: false
  slack:
    secure: tJL+DDfkvgD8y2xC9bkDiKtBg1/n2e/LniUtjaA/AXAoCpzBi9CWpBiEyRsfVKAgZ9j7skod/xFlKp3HyO66O7E6GdYSpe5sQobEVq7x0j/EqQCAZmJDojdzkpF9ExUk0wQ3kVGVeT6ykI8EmSWwBb9KFyocEF6lGB+O29w1hr1eCL+3UkpU6tPdLOncuzfys8/Jdhro6KGN249aiy4cdAJJEjT5Iv+QqKsgqQbuJbwc4agaEA9rCabE/XZE3NyuVIiKuPkP8XCy7G2ljvbL0lOp7EGZvtnXGOgg1rKZmzn1ZSNT2nov5tiVXSu+rhjoaErq6cfeMkVRuo9vSZId5YiCbaMPbevsShcYmvSj+mYestRfJaAQ/Tn8DNZYy6UnoqyZPIZiCTtLNQ2/NZFS2JDFyqUdA5TFcPcyyAtiLiGJcIOlkB0oICAzwbJVXe8/fHmn0+3b+45/sn4FZK/RFIQfIgvk7/U+5zuKafhGbs2VDg6T9F7jCypfUSQIGeEtsyFGLyOed2mpiEN3bzgnJvvU01HtiQo+cZpwWvDwyQK3HmymmaKHeWh478zBtdHUoTbNfwmUZIJAY6RKrn6GHYWs97gYOSM2dF2+O6dYZ/Y4XIbxynloErPYqyj2INV7G/fjFRpXnOTlsMQrHUxlYCIVIbpM92PxBlirMEItLmY=
